# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

def yy():
    print("aaa")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 367)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 22))
        self.menubar.setObjectName("menubar")
        self.menushentouceshi = QtWidgets.QMenu(self.menubar)
        self.menushentouceshi.setObjectName("menushentouceshi")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsql = QtWidgets.QAction(MainWindow)
        self.actionsql.setObjectName("actionsql")
        self.actioncobalt_strike = QtWidgets.QAction(MainWindow)
        self.actioncobalt_strike.setObjectName("actioncobalt_strike")
        self.action_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.action_3.setFont(font)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.actionSeay = QtWidgets.QAction(MainWindow)
        self.actionSeay.setObjectName("actionSeay")
        self.menushentouceshi.addAction(self.actionsql)
        self.menushentouceshi.addSeparator()
        self.menushentouceshi.addAction(self.actioncobalt_strike)
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addSeparator()
        self.menu.addAction(self.action_7)
        self.menu_2.addAction(self.action_9)
        self.menu_3.addAction(self.actionSeay)
        self.menubar.addAction(self.menushentouceshi.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)

        self.menubar.triggered['QAction*'].connect(yy)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "天河平台"))
        self.menushentouceshi.setTitle(_translate("MainWindow", "渗透测试"))
        self.menu.setTitle(_translate("MainWindow", "免杀工具"))
        self.menu_2.setTitle(_translate("MainWindow", "代理工具"))
        self.menu_3.setTitle(_translate("MainWindow", "审计工具"))
        self.actionsql.setText(_translate("MainWindow", "sql盲注多线程"))
        self.actioncobalt_strike.setText(_translate("MainWindow", "cobalt strike"))
        self.action_3.setText(_translate("MainWindow", "免杀一代"))
        self.action_5.setText(_translate("MainWindow", "免杀二代"))
        self.action_7.setText(_translate("MainWindow", "特征码分块工具"))
        self.action_9.setText(_translate("MainWindow", "蚁剑"))
        self.actionSeay.setText(_translate("MainWindow", "Seay"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui_zhuye = Ui_MainWindow()
    ui_zhuye.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())