# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import _thread
import os
import sys
import json
from PyQt5 import QtCore, QtGui, QtWidgets
#添加分类
def fenlei_click():
    {}

#添加子菜单

#删除子菜单
def shanchu_click():
    {}


def yy(a):
    os.system(a.data())



class Ui_MainWindow(QtWidgets.QMainWindow):

    def shanchu_click(self):
        os.system("python ./shanchu.py")

    def shanchu_mokuai_click(self):
        os.system("python ./shanchu_gongju.py")

    def tianjia_caidan_click(self):
        os.system("python ./tianjia_mokuai.py")
    def tianjia_click(self):
        os.system("python ./tianjia.py")

    def setupUi(self, MainWindow):
        with open("./config/config.json","r",encoding='UTF-8') as file:
            # tt = file.read()
            # text = tt.decode("gbk").encode("utf-8")
            data = json.load(file)  #config文件的配置信息转字典

        self.list_menu = []


        #获取定义名
        _translate = QtCore.QCoreApplication.translate

        #获取menubar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 533, 80))
        self.menubar.setObjectName("menubar")

        #菜单栏循环读取
        for i in data:
            self.menu = QtWidgets.QMenu(self.menubar)
            self.menu.setObjectName(i)
            self.list_menu.append(self.menu)
            self.menu.setTitle(_translate("MainWindow", i))
            #循环向菜单中添加子菜单
            for i_2 in data[i]:
                self.action = QtWidgets.QAction(MainWindow)
                self.action.setObjectName(i_2)
                self.action.setText(_translate("MainWindow", i_2))
                self.menu.addAction(self.action)
                self.action.setData(data[i][i_2])

            self.menubar.addAction(self.menu.menuAction())
            self.menu.addSeparator()
        MainWindow.setMenuBar(self.menubar)
        self.menubar.triggered['QAction*'].connect(yy)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/Saved Pictures/165135-16321278956369.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 530, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 50, 240, 240))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ico.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 500, 200))
        self.textBrowser.setObjectName("textBrowser")

        #按钮
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 300, 180, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 300, 180, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 300, 180, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 300, 180, 40))
        self.pushButton_4.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)



        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)


        self.pushButton_4.clicked.connect(self.shanchu_click)
        self.pushButton.clicked.connect(self.tianjia_click)
        self.pushButton_2.clicked.connect(self.shanchu_mokuai_click)
        self.pushButton_3.clicked.connect(self.tianjia_caidan_click)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "天河平台"))

        self.label.setText(_translate("MainWindow", "天河渗透测试多工具自定义平台"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:18px; color:#59c3f9; background-color:rgba(254,254,254,0.494118);\">    此软件仅用于学习，由于传播、利用此软件所造成的任何直接或者间接的后果及损失，均由使用者本人负责，作者不为此承担任何责任。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'微软雅黑\',\'sans-serif\'; font-size:18px; color:#59c3f9;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\',\'sans-serif\'; font-size:18px; color:#59c3f9; background-color:rgba(254,254,254,0.494118);\">    总是梦见云层之上飞过子午线。     --日落大道</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "添加工具"))
        self.pushButton_2.setText(_translate("MainWindow", "删除工具"))
        self.pushButton_3.setText(_translate("MainWindow", "添加分类"))
        self.pushButton_4.setText(_translate("MainWindow", "删除分类"))




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui_zhuye = Ui_MainWindow()
    ui_zhuye.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())